### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by cmiller734** [fantasyui-com/readme-editor#1]
After running the npm install and 'epx readme-editor', I got this error:

async function main(){
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

**Comment by fantasyui-com** [comment]
Unexpected token function at async probably means you have an old electron installation. I revisited this program after a long while and found my electron was outdated too, my error was about the require function. Electron is in constant development, it is always good to do npm install electron@latest or similar.

My collection of electron applications are unique in the sense that they do minimal modifications to the way electron applications behave. I really just edit the HTML and later the render.js which is about as separate from the world of electron as it gets.

I am now going through all my electron apps to ensure they work with the latest electron.
